/icp_registration:
  ros__parameters:
    use_sim_time: false 
    rough_leaf_size: 0.5
    refine_leaf_size: 0.1
    pcd_path: "src/localization/Point-LIO-grid_map_ros2/PCD/601.pcd"
    map_frame_id: "map"
    odom_frame_id: "odom"
    laser_frame_id: "aft_mapped"
    pointcloud_topic: "/livox/lidar/pointcloud"
    thresh: 0.04
    xy_offset: 15.0
    yaw_offset: 30.0
    yaw_resolution: 3.0
    initial_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # x,y,z,roll,pitch,yaw